### ISSUE TITLE
output differ from ls

### ISSUE THREAD

**Issue by nkh** [trapd00r/File-LsColor#1]
Hi,
file 'abc' which is a perl ascii text executable, is not displayed with the executable color as ls does.

I tried ls_color and ls_color_custom($ENV{LS_COLORS}, $path), both color wrong.

**Comment by trapd00r** [comment]
I wonder if this really can be implemented in a good way that doesn't take away any usefulness of the module. When I use it myself I don't always care for if the files do exist or not, or where in the filesystem they reside. I might only be interested in the basenames, and given many complex operations on the cmdline, stat():ing the files will just not work.

What we can do, however, is to honor the extra attributes like directory, executable etc when given either absolute paths or called from ./. Working on it right now.

**Comment by nkh** [comment]
There is this too that I have started using

https://github.com/sharkdp/lscolors

**Comment by trapd00r** [comment]
This is now fixed, thanks for reporting.
![ls_color](https://raw.githubusercontent.com/trapd00r/File-LsColor/master/extra/ls_color_pacman.png)
