### ISSUE TITLE
Issues link on MetaCPAN

### ISSUE THREAD

**Issue by eserte** [trapd00r/File-LsColor#4]
MetaCPAN currently links to https://rt.cpan.org/Public/Dist/Display.html?Name=File-LsColor if clicking on the "Issues" link (on https://metacpan.org/release/WOLDRICH/File-LsColor-0.492 ). However, RT says that the correct issue tracker is on github. What's correct?

(Maybe the problem is that once META.* explicitly listed the github issues tracker, but now it does not anymore)

**Comment by trapd00r** [comment]
That's weird. 
Shouldn't https://metacpan.org/source/WOLDRICH/File-LsColor-0.492/Makefile.PL#L13 be enough?

**Comment by eserte** [comment]
The bugtracker is not listed in the yaml version of META.*: https://metacpan.org/source/WOLDRICH/File-LsColor-0.492/META.yml#L23

There's something in the json version. However I am surprised that it's spelled `x_bugtracker` --- shouldn't it be `bugtracker` without the `x_` prefix?

**Comment by trapd00r** [comment]
After digging through CPAN::Meta::Spec I discovered that the bugtracker meta key should reside on its own and not be part of the repository map.

```
      bugtracker => {
        web    => q{https://github.com/trapd00r/File-LsColor/issues},
        mailto => q{m@japh.se},
      },
      repository => {
        type  => 'git',
        url   => 'https://github.com/trapd00r/File-LsColor.git',
        web   => 'https://github.com/trapd00r/File-LsColor',
      },
```
Thank you, closing this now with the knowledge that I'll have to redo all of my Makefile.PL's. :smile:
