### ISSUE TITLE
ls_colors doesn't put colors when the extension is in capital case

### ISSUE THREAD

**Issue by florian-pe** [trapd00r/File-LsColor#9]
I remarked that ls_colors, both the terminal and the module subroutine doesn't colorize filenames which have capital case.
For example, 
viddeo.MP4 and video.MKV aren't colorized.
I have tested it and they are colored, though, when using the ls command:  ls *.MP4 *.MKV

It would be nice if this module could do it because it's not that uncommon to download files that an extension that is capitalized.
Thank you !

**Comment by trapd00r** [comment]
Hi @florian-pe, 

Thank you for reaching out.
I've introduced the $File::LsColor::IGNORE_CASE variable that can be set to a true value if one wishes to ignore the case.

Furthermore, I've added a new [ls_color_ignorecase](https://github.com/trapd00r/File-LsColor/blob/master/bin/ls_color_ignorecase) tool that will do that for you.
